language: python

python:
    - "3.6"
    - "3.7"

env:
    global:
        - PIPENV_VENV_IN_PROJECT=1
        - PIPENV_IGNORE_VIRTUALENVS=1

install:
    - pip install pipenv
    - pipenv install --dev --three

script:
    - mkdir ~/.config
    - cp ./setup.cfg ~/.config/pycodestyle
    - pipenv run pycodestyle .
    - pipenv run pydocstyle .

test:
    - pipenv run python -m unittest discover

